### PR TITLE
Add Discount resource

### LINKED ISSUE #25: complete Discount resource
complete [Discount](https://docs.shopify.com/api/discount) with integration tests

### PR DESCRIPTION
**Pull request by lpinca**
This adds the [Discount](https://docs.shopify.com/api/discount) resource.
Closes #25.

### CODE REVIEW

**Comment by Alua-Kinzhebayeva** [comment]
Could you please change " it('should destroy a carrier service'" to "a discount" before I merge this PR?

**Comment by lpinca** [comment]
Sure, some copy/paste leftover there :smile:

**Comment by Alua-Kinzhebayeva** [comment]
;)

**Comment by lpinca** [comment]
Done.

**Pull request merged**
