### PR TITLE
Added a few more api endpoints

### PR DESCRIPTION
**Pull request by aquint**

### CODE REVIEW

**Comment by alexandresaiz** [comment]
@aquint thanks! Will take a look and if it's ok, merge! Can you share your email address?

**Comment by aquint** [comment]
Great! Thanks for the repo, you can reach me at anthonyquinton92@gmail.com

**Comment by Alua-Kinzhebayeva** [comment]
Hi, @aquint ! 
asset.js
I have created an integration test for this resource https://gist.github.com/Alua-Kinzhebayeva/7385bcdbc91c7814d815, and removed
Asset.prototype.all = function(parentId, params, callback) {
      var url, _ref;
      if (typeof params === 'function') {
        _ref = [callback, params], params = _ref[0], callback = _ref[1];
      }
      url = "" + this.prefix + "/" + parentId + this.child + "?" + params;

      return this.resource.get(url, "" + this.slug , callback);
    };

Redefinition of Asset.prototype.all breaks logic for “/admin/themes/828155753/assets.json: Listing theme assets only returns metadata about each asset. You need to request assets individually in order to get their contents.”. When we call /admin/themes/828155753/assets.json it returns  us “assets”.  With new function it will try to find “asset”.
I guess it’s been done to handle other invocations of “/admin/themes/828155753/assets.json” which return “asset”. If you don’t mind me suggesting, what if we define separate function(s) for cases with “asset”?

metafield.js
I have created integration test metafield_test.js https://gist.github.com/Alua-Kinzhebayeva/f892eead5da0f2bf4bec
createForShop passed successfully, but deleteFromShop fails due to wrong url  "https://test.myshopify.com/admin//metafields/721389482.json" .
This line  breaks the url: "url = this.resource.queryString("" + this.prefix + "/" + this.child + "/" + id);" If we change url to "url = this.resource.queryString("" + this.prefix + this.child + "/" + id);", it will fix it.

And minor things are console.log(s) left from debugging/testing. Removing them from Resource.js/Base_child.js would have been brilliant. 

P.S. if you decide to run tests I was talking about, you would need jsons. I got them from API pages like https://docs.shopify.com/api/asset#index

**Comment by alexandresaiz** [comment]
@Alua-Kinzhebayeva if you agree, I will close this PR.

**Comment by Alua-Kinzhebayeva** [comment]
@alexandresaiz sure

**Comment by alexandresaiz** [comment]
Closing due to previously mentioned reasons.

**Pull request closed without merging**
